export const AGENCY_REGISTER_REQUEST = 'AGENCY_REGISTER_REQUEST'
export const AGENCY_REGISTER_SUCCESS = 'AGENCY_REGISTER_SUCCESS'
export const AGENCY_REGISTER_FAIL = 'AGENCY_REGISTER_FAIL'

export const AGENCY_LIST_REQUEST = 'AGENCY_LIST_REQUEST'
export const AGENCY_LIST_SUCCESS = 'AGENCY_LIST_SUCCESS'
export const AGENCY_LIST_FAIL = 'AGENCY_LIST_FAIL'