export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST'
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS'
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL'

export const CAR_DELETE_REQUEST = 'CAR_DELETE_REQUEST'
export const CAR_DELETE_SUCCESS = 'CAR_DELETE_SUCCESS'
export const CAR_DELETE_FAIL = 'CAR_DELETE_FAIL'

export const CAR_ADD_REQUEST = 'CAR_ADD_REQUEST'
export const CAR_ADD_SUCCESS = 'CAR_ADD_SUCCESS'
export const CAR_ADD_FAIL = 'CAR_ADD_FAIL'

export const CAR_NUMBER_REQUEST = 'CAR_NUMBER_REQUEST'
export const CAR_NUMBER_SUCCESS = 'CAR_NUMBER_SUCCESS'
export const CAR_NUMBER_FAIL = 'CAR_NUMBER_FAIL'

export const CAR_UPDATE_REQUEST = 'CAR_UPDATE_REQUEST'
export const CAR_UPDATE_SUCCESS = 'CAR_UPDATE_SUCCESS'
export const CAR_UPDATE_FAIL = 'CAR_UPDATE_FAIL'