export const ADD_CONTRACT_REQUEST = 'ADD_CONTRACT_REQUEST'
export const ADD_CONTRACT_SUCCESS = 'ADD_CONTRACT_SUCCESS'
export const ADD_CONTRACT_FAIL = 'ADD_CONTRACT_FAIL'

export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_FAIL = 'CONTRACT_LIST_FAIL'

export const DELETE_CONTRACT_REQUEST = 'DELETE_CONTRACT_REQUEST'
export const DELETE_CONTRACT_SUCCESS = 'DELETE_CONTRACT_SUCCESS'
export const DELETE_CONTRACT_FAIL = 'DELETE_CONTRACT_FAIL'