export const EXPENSE_LIST_REQUEST = 'EXPENSE_LIST_REQUEST'
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS'
export const EXPENSE_LIST_FAIL = 'EXPENSE_LIST_FAIL'

export const EXPENSE_DELETE_REQUEST = 'EXPENSE_DELETE_REQUEST'
export const EXPENSE_DELETE_SUCCESS = 'EXPENSE_DELETE_SUCCESS'
export const EXPENSE_DELETE_FAIL = 'EXPENSE_DELETE_FAIL'

export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL'

export const UPDATE_EXPENSE_REQUEST = 'UPDATE_EXPENSE_REQUEST'
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS'
export const UPDATE_EXPENSE_FAIL = 'UPDATE_EXPENSE_FAIL'

export const CHART_EXPENSE_REQUEST = 'CHART_EXPENSE_REQUEST'
export const CHART_EXPENSE_SUCCESS = 'CHART_EXPENSE_SUCCESS'
export const CHART_EXPENSE_FAIL = 'CHART_EXPENSE_FAIL'